import { descriptions } from "./descriptions";
import { handlers } from "./handlers";

export const TaskNames = [
  "DELVE",
  "WILDY_BOSSES",
  "PULLING",
  "CG",
  "DT2",
  "RAIDS",
  "GETTING_HEAD",
  "CONTRACT_SKILLER",
  "NICE_ROD",
] as const;

export const taskList = {
  delve: {
    name: "DELVE",
    label: "Delve Tile",
    description: descriptions.delve.task,
    requirements: descriptions.delve.requirements,
    drops: ["mokhaiotl cloth", "eye of ayak (uncharged)", "avernic treads"],
    skills: [],
    bosses: [],
    tiers: {
      1: {
        description: descriptions.delve.tiers[1].description,
        requirements: descriptions.delve.tiers[1].requirements,
        points: 20,
        isComplete: handlers.delve.tierOne,
      },
      2: {
        description: descriptions.delve.tiers[2].description,
        requirements: descriptions.delve.tiers[2].requirements,
        points: 30,
        isComplete: handlers.delve.tierTwo,
      },
      3: {
        description: descriptions.delve.tiers[3].description,
        requirements: descriptions.delve.tiers[3].requirements,
        points: 40,
        isComplete: handlers.delve.tierThree,
      },
    },
  },
  wildy: {
    name: "WILDY_BOSSES",
    label: "Wildy Boss Tile",
    description: descriptions.wildy.task,
    requirements: descriptions.wildy.requirements,
    drops: [
      "claws of callisto",
      "fangs of venenatis",
      "skull of vet'ion",
      "voidwaker gem",
      "voidwaker hilt",
      "voidwaker blade",
      "dragon 2h sword",
      "dragon pickaxe",
      "tyrannical ring",
      "ring of the gods",
      "treasonous ring",
    ],
    skills: [],
    bosses: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.wildy.tiers[1].requirements,
        points: 30,
        isComplete: handlers.wildy.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.wildy.tiers[2].requirements,
        points: 15,
        isComplete: handlers.wildy.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.wildy.tiers[3].requirements,
        points: 15,
        isComplete: handlers.wildy.tierThree,
      },
    },
  },
  pulling: {
    name: "PULLING",
    label: "Pulling Tile",
    description: descriptions.pulling.task,
    requirements: descriptions.pulling.requirements,
    drops: [
      "catalytic talisman",
      "elemental talisman",
      "abyssal needle",
      "abyssal lantern",
      "abyssal blue dye",
      "abyssal green dye",
      "abyssal red dye",
      "bow string spool",
      "fletching knife",
      "greenman mask",
      "tackle box",
      "big harpoonfish",
      "fish barrel",
      "tome of water (empty)",
      "dragon harpoon",
    ],
    skills: [],
    bosses: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.pulling.tiers[1].requirements,
        points: 30,
        isComplete: handlers.pulling.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.pulling.tiers[2].requirements,
        points: 30,
        isComplete: handlers.pulling.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.pulling.tiers[3].requirements,
        points: 60,
        isComplete: handlers.pulling.tierThree,
      },
    },
  },
  cg: {
    name: "CG",
    label: "Corrupted Gauntlet Tile",
    description: descriptions.cg.task,
    requirements: descriptions.cg.requirements,
    drops: [
      "crystal weapon seed",
      "crystal armour seed",
      "enhanced crystal weapon seed",
      "enhanced crystal teleport seed",
    ],
    skills: [],
    bosses: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.cg.tiers[1].requirements,
        points: 55,
        isComplete: handlers.cg.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.cg.tiers[2].requirements,
        points: 20,
        isComplete: handlers.cg.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.cg.tiers[3].requirements,
        points: 10,
        isComplete: handlers.cg.tierThree,
      },
    },
  },
  dt2: {
    name: "DT2",
    label: "DT2 Bosses Tile",
    description: descriptions.dt2.task,
    drops: [
      "awakener's orb",
      "ice quartz",
      "smoke quartz",
      "shadow quartz",
      "blood quartz",
      "virtus robe top",
      "virtus robe bottom",
      "virtus mask",
      "magus vestige",
      "venator vestige",
      "bellator vestige",
      "ultor vestige",
      "eye of the duke",
      "leviathan's lure",
      "siren's staff",
      "executioner's axe head",
      "gold ring",
    ],
    skills: [],
    bosses: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.dt2.tiers[1].requirements,
        points: 10,
        isComplete: handlers.dt2.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.dt2.tiers[2].requirements,
        points: 70,
        isComplete: handlers.dt2.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.dt2.tiers[3].requirements,
        points: 80,
        isComplete: handlers.dt2.tierThree,
      },
    },
  },
  raids: {
    name: "RAIDS",
    label: "Raids Tile",
    description: descriptions.raids.task,
    requirements: descriptions.raids.requirements,
    drops: [
      "masori mask",
      "masori body",
      "masori chaps",
      "lightbearer",
      "osmumten's fang",
      "eildinis' ward",
      "tumeken's shadow",
      "avernic defender hilt",
      "justiciar faceguard",
      "justiciar chestguard",
      "justiciar lagguard",
      "ghrazi rapier",
      "sanguinesti staff",
      "scyth of vitur",
      "twisted buckler",
      "arcane prayer scroll",
      "dexterous prayer scroll",
      "dragon hunter crossbow",
      "dinh's bulwark",
      "ancestral hat",
      "ancestral robe top",
      "ancestral robe bottom",
      "dragon claws",
      "kodai insignia",
      "twisted bow",
    ],
    bosses: [
      "chambers_of_xeric",
      "chambers_of_xeric_challenge_mode",
      "theater_of_blood",
      "theater_of_blood_hard_mode",
      "tombs_of_amascut",
      "tombs_of_amascut_expert",
    ],
    skills: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.raids.tiers[1].requirements,
        points: 50,
        isComplete: handlers.raids.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.raids.tiers[2].requirements,
        points: 100,
        isComplete: handlers.raids.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.raids.tiers[3].requirements,
        points: 50,
        isComplete: handlers.raids.tierThree,
      },
    },
  },
  slayer: {
    name: "GETTING_HEAD",
    label: "Getting Head Tile",
    description: descriptions.delve.task,
    requirements: descriptions.delve.requirements,
    drops: [
      "imbued heart",
      "dragon warhammer",
      "basilisk jaw",
      "mist battlestaff",
      "dust battlestaff",
      "eternal gem",
      "abyssal head",
      "araxyte head",
      "alchemical hydra head",
      "basilisk head",
      "cockatrice head",
      "kbd heads",
      "kq head",
      "kurask head",
      "vorkath's head",
    ],
    skills: ["slayer"],
    bosses: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.slayer.tiers[1].requirements,
        points: 40,
        isComplete: handlers.slayer.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.slayer.tiers[2].requirements,
        points: 40,
        isComplete: handlers.slayer.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.slayer.tiers[3].requirements,
        points: 70,
        isComplete: handlers.slayer.tierThree,
      },
    },
  },
  skilling: {
    name: "CONTRACT_SKILLER",
    label: "Contract (s)killer Tile",
    description: descriptions.skilling.task,
    requirements: descriptions.skilling.requirements,
    drops: [
      "guild hunter headgear",
      "guild hunter top",
      "guild hunter legs",
      "guild hunter boots",
      "gnome scarf",
    ],
    skills: ["cooking", "smithing", "hunter"],
    bosses: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.skilling.tiers[1].requirements,
        points: 15,
        isComplete: handlers.skilling.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.skilling.tiers[2].requirements,
        points: 25,
        isComplete: handlers.skilling.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.skilling.tiers[3].requirements,
        points: 40,
        isComplete: handlers.skilling.tierThree,
      },
      4: {
        description: "",
        requirements: descriptions.skilling.tiers[4].requirements,
        points: 20,
        isComplete: handlers.skilling.tierThree,
      },
    },
  },
  rod: {
    name: "NICE_ROD",
    label: "Nice Rod Tile",
    description: descriptions.rod.task,
    drops: [
      "uncharged trident",
      "trident of the seas (full)",
      "pharaoh's scepter",
      "ancient icon",
    ],
    skills: [],
    bosses: [],
    tiers: {
      1: {
        description: "",
        requirements: descriptions.rod.tiers[1].requirements,
        points: 25,
        isComplete: handlers.rod.tierOne,
      },
      2: {
        description: "",
        requirements: descriptions.rod.tiers[2].requirements,
        points: 35,
        isComplete: handlers.rod.tierTwo,
      },
      3: {
        description: "",
        requirements: descriptions.rod.tiers[3].requirements,
        points: 40,
        isComplete: handlers.rod.tierThree,
      },
    },
  },
};
